#!/usr/bin/env python3

import rospy
from ultralytics import YOLO
from sensor_msgs.msg import Image
from std_msgs.msg import String
import ros_numpy as rosnp

def img_callback(data):
    global array, class_pub, det_image_pub
    array = rosnp.numpify(data)
    det_result = model(array)
    det_annotated = det_result[0].plot(show=False)
    det_image_pub.publish(rosnp.msgify(Image, det_annotated, encoding="utf-8"))

    classes = det_result[0].boxes.cls.cpu().numpy().astype(int)
    names = [det_result[0].names[i] for i in classes]

    class_pub.publish(String(data=str(names)))

MODEL = 'yolov8_obb_finetuned.pt'
model = YOLO(MODEL)

rospy.init_node("yolo_detection")
rospy.Subscriber("camera", Image, img_callback)

det_image_pub = rospy.Publisher("detected_objects", Image, queue_size=5)
class_pub = rospy.Publisher("detected_classes", String, queue_size=5)

rospy.spin()
