#!/usr/bin/env python3
import pyvirtualcam
import ros_numpy as rosnp
import rospy
from sensor_msgs.msg import CameraInfo, Image


def img_callback(msg, virtual_camera):
    img = rosnp.numpify(msg)[:, :, :3]
    img = img[:, :, ::-1]
    virtual_camera.send(img)


if __name__ == "__main__":
    rospy.init_node("virtual_camera")
    camera_info = rospy.wait_for_message("~camera_info", CameraInfo)
    device = rospy.get_param("~device", "/dev/video0")
    cam = pyvirtualcam.Camera(
        width=camera_info.width, height=camera_info.height, fps=30, device=device
    )
    print(f"Using virtual camera {cam.device}")
    rospy.Subscriber("~image", Image, img_callback, cam)
    rospy.spin()
