#!/usr/bin/env python3
import rospy
import pyvirtualcam
import ros_numpy as rosnp
from sensor_msgs.msg import Image


def img_callback(msg, virtual_camera):
    img = rosnp.numpify(msg)[:, :, :3]
    img = img[:, :, ::-1]
    virtual_camera.send(img)


if __name__ == "__main__":
    rospy.init_node("virtual_camera")
    # TODO: Read camera information from ROS
    cam = pyvirtualcam.Camera(width=2048, height=1536, fps=30)
    print(f"Using virtual camera {cam.device}")
    rospy.Subscriber("rgb", Image, img_callback, cam)
    rospy.spin()
